<?php
session_start();
define('incl_path','../../global/libs/');
define('libs_path','../../libs/');
define('mail_path','../../global/PHPMailer/');
require_once(incl_path.'gfconfig.php');
require_once(incl_path.'gfinit.php');
require_once(incl_path.'gffunc.php');
require_once(incl_path.'gffunc_member.php');
require_once(libs_path.'cls.mysql.php');
require_once(mail_path.'mail.php');
$arr=array();
$par_user=isset($_COOKIE['RES_USER'])?decrypt($_COOKIE['RES_USER']):'';
$arr['username']=isset($_POST['username'])?antiData($_POST['username']):'';
$arr['password']=isset($_POST['password'])?antiData($_POST['password']):'';
$arr['fullname']=isset($_POST['fullname'])?antiData($_POST['fullname']):'';
$arr['par_user']=$par_user;
unset($_POST);
if($arr['username']=='' || $arr['password']=='') die('Username and Password are empty');
$arr['password']=hash('sha256',$arr['username']).'|'.hash('sha256',md5($arr['password']));
$data=array();
$data['regis_data']=encrypt(json_encode($arr,JSON_UNESCAPED_UNICODE),PIT_API_KEY);
$url=ROOTHOST.'api/member/regis';
$rep=Curl_Post($url,json_encode($data));
if($rep['status']=='no') die($rep['mess']);
else{
	$result=file_get_contents(ROOTHOST."api/mem/sendmail_verifyAccount.php?username=".$arr['username']);
	die('success');
}
unset($data);
unset($rep);
unset($arr);